baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "systematik" 


[[menu.main]]
    name = "Home"
    title = "home section"
    weight = 10
    identifier = "home"
    url = "/"
    
    
[[menu.main]]
    name = "Dokumentation"
    title = "Dokumentation section"
    weight = 20
    identifier = "Dokumentation"
    url = "/Dokumentation/"
    
    
[[menu.main]]
    name = "Dokumentation"
    title = "Dokumentation section"
    weight = 20
    identifier = "Dokumentation"
    url = "/Dokumentation/"
